org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=34
# Use Flutter built-in Kotlin support and the new Gradle DSL
android.builtInKotlin=true
android.newDsl=true
